name: Closed-Pr-Label
on:
  pull_request:
     types:
        - closed

jobs:
   closed_label:
      runs-on: ubuntu-latest
      permissions:
         issues: write-all
      steps:
        - run: gh pr edit "$NUMBER" --add-label "$LABELS"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.number }}
          LABELS: closed

   comment-on-issue:
       runs-on: ubuntu-latest
       steps:
        - name: "dump github actions"
          run: echo '${{ toJSON(github.event ) }}' | jq
          shell: bash
