name: Add comment On Creating Issue
on:
  issues:
    types:
      - [opened]
jobs:
  add-comment-on-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment on Issue
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This issue is created by github gh on
            creating a new Issue it will trigger
            
