name: Hello world Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: hello world
         run: echo "hello world"
         shell: bash
 
  goodBye:
    runs-on: ubuntu-latest
    steps:
       - name: Good Byeee
         run: echo "good byee"
         shell: bash
